spring.application.name=FootballTicket

#database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=myapp;encrypt=true;trustServerCertificate=true
spring.datasource.username=SA
spring.datasource.password=YourStronG!Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.check-template-location=true

# Spring MVC - HTTP
spring.mvc.hiddenmethod.filter.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Security
# ????????? Security ??? ??????????
spring.security.enabled=false

# ??????????? ?? ?????????
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.default-page-size=20

# ?????? ?? ??????? ??????? ????????
server.max-http-request-header-size=8KB

spring.devtools.restart.enabled=true

# Session 30 days
server.servlet.session.timeout=2592000

spring.cache.type=simple
spring.cache.cache-names=categories,dishes,promotions,dashboard,orders

server.compression.enabled=true
server.compression.mime-types=text/html,text/css,application/javascript,image/png,image/jpeg

spring.web.resources.cache.cachecontrol.max-age=31536000
spring.web.resources.cache.cachecontrol.cache-public=true


# ?????? ?? XSS (????? ??????)
# ??????? ????? ? SecurityConfig



#port
server.port=8081

#DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG